[2025-01-31T03:20:10.688+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T03:20:10.705+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.check_table_branch_task manual__2025-01-31T03:20:07.463730+00:00 [queued]>
[2025-01-31T03:20:10.714+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.check_table_branch_task manual__2025-01-31T03:20:07.463730+00:00 [queued]>
[2025-01-31T03:20:10.715+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-01-31T03:20:10.730+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): check_table_branch_task> on 2025-01-31 03:20:07.463730+00:00
[2025-01-31T03:20:10.743+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=430) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T03:20:10.745+0000] {standard_task_runner.py:72} INFO - Started process 432 to run task
[2025-01-31T03:20:10.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_and_insert_csv_to_postgres_with_branch_adjusted', 'check_table_branch_task', 'manual__2025-01-31T03:20:07.463730+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/read_file_updated.py', '--cfg-path', '/tmp/tmp8_qlkui2']
[2025-01-31T03:20:10.747+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask check_table_branch_task
[2025-01-31T03:20:10.796+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.check_table_branch_task manual__2025-01-31T03:20:07.463730+00:00 [running]> on host e2498a6c8083
[2025-01-31T03:20:10.871+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_and_insert_csv_to_postgres_with_branch_adjusted' AIRFLOW_CTX_TASK_ID='check_table_branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T03:20:07.463730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T03:20:07.463730+00:00'
[2025-01-31T03:20:10.873+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-31T03:20:10.873+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-31T03:20:10.874+0000] {logging_mixin.py:190} INFO - Current task name:check_table_branch_task state:running start_date:2025-01-31 03:20:10.706546+00:00
[2025-01-31T03:20:10.875+0000] {logging_mixin.py:190} INFO - Dag name:validate_and_insert_csv_to_postgres_with_branch_adjusted and current dag run status:running
[2025-01-31T03:20:10.875+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T03:20:10.876+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-31T03:20:10.886+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-01-31T03:20:10.893+0000] {logging_mixin.py:190} INFO - Employee Data table exists. Proceeding to check files.
[2025-01-31T03:20:10.894+0000] {python.py:240} INFO - Done. Returned value was: check_files_branch_task
[2025-01-31T03:20:10.894+0000] {branch.py:38} INFO - Branch into check_files_branch_task
[2025-01-31T03:20:10.895+0000] {skipmixin.py:230} INFO - Following branch ('check_files_branch_task',)
[2025-01-31T03:20:10.906+0000] {skipmixin.py:278} INFO - Skipping tasks [('create_table_employee_data_task', -1)]
[2025-01-31T03:20:10.956+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T03:20:10.957+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=validate_and_insert_csv_to_postgres_with_branch_adjusted, task_id=check_table_branch_task, run_id=manual__2025-01-31T03:20:07.463730+00:00, execution_date=20250131T032007, start_date=20250131T032010, end_date=20250131T032010
[2025-01-31T03:20:10.965+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-31T03:20:10.966+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-31T03:20:10.967+0000] {logging_mixin.py:190} INFO - Dag name:validate_and_insert_csv_to_postgres_with_branch_adjusted queued_at:2025-01-31 03:20:07.483472+00:00
[2025-01-31T03:20:10.968+0000] {logging_mixin.py:190} INFO - Task hostname:e2498a6c8083 operator:BranchPythonOperator
[2025-01-31T03:20:11.001+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T03:20:11.030+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T03:20:11.035+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
